### ISSUE TITLE
Conflit avec Anti Virus

### ISSUE THREAD

**Issue by ZestyEagle** [Symbian9/qmapshack-doc-wiki#1]
![Conflit](https://user-images.githubusercontent.com/98384740/151664084-940fd467-9e77-4f03-ae20-a32c0a9093e0.jpg)

**Comment by ZestyEagle** [comment]
Il semble que QmapShack, tente de modifier ou sauvegarder du PNG.
Est ce normal ou?

**Comment by Symbian9** [comment]
@ZestyEagle, You posted in wrong repo)

Here is official QMapShack repo on GitHub:

- https://github.com/Maproom/qmapshack

Please, report issues in official repo.
